Use proper programmatic Composer install steps.

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -36,9 +36,17 @@ install_php() {
         # make test || exit 1
         make install || exit 1
 
-        ${install_path}/bin/php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
-        ${install_path}/bin/php -r "if (hash_file('sha384', 'composer-setup.php') === '48e3236262b34d30969dca3c37281b3b4bbe3221bda826ac6a9a62d6444cdb0dcd0615698a5cbe587c3f0fe57a54d8f5') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
-        ${install_path}/bin/php composer-setup.php --install-dir=${install_path}/bin --filename=composer
+        php=${install_path}/bin/php
+        EXPECTED_SIGNATURE="$(curl -s https://composer.github.io/installer.sig)"
+        ACTUAL_SIGNATURE="$(${php} -r "echo hash_file('sha384', 'composer-setup.php');")"
+        if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+        then
+            >&2 echo 'ERROR: Invalid installer signature'
+            rm composer-setup.php
+            exit 1
+        fi
+
+        ${php} composer-setup.php --install-dir=${install_path}/bin --filename=composer
     )
 }
 
